name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Só fazer deploy nas mudanças na branch main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build do projeto
      - name: Build project
        run: vite build

      # 5. Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist  # Diretório gerado pelo Vite
